### ISSUE TITLE
Add support for setting ThisAssembly namespace

### ISSUE THREAD

**Issue by kzu** [devlooped/ThisAssembly#211]
And it should be consistent across all packages.

**Comment by kzu** [comment]
Will wait for upvotes to see if this is something folks really need/want...

**Comment by jakenuts** [comment]
Perhaps? I just started receiving errors relating to XUnit, CommunityToolkit.Diagnostics having internal ThisAssembly fields and I can't seem to get past them. Not sure how to scope the reference since even the using namespace stuff sees it as an internal class from those packages.

![image](https://github.com/devlooped/ThisAssembly/assets/344606/22a3d340-f572-46c4-8aa8-32984fc5eb56)

**Comment by kzu** [comment]
Temporarily closing due to a lack of interest.
