### ISSUE TITLE
Generated files should include `/// <auto-generated/>` preamble

### ISSUE THREAD

**Issue by AArnott** [devlooped/ThisAssembly#273]
## Describe the Bug

When these source generators are used in a project with Stylecop.Analyzers, diagnostics are produced that can block adoption.

## Steps to Reproduce

Install `StyleCop.Analyzers` into a project that uses the `ThisAssembly.Resource` package.
Build.

## Expected Behavior

No warnings

## Actual behavior

Warnings such as this:

> ThisAssembly.Resource\ThisAssembly.ResourcesGenerator\ThisAssembly.Resources.EmbeddedResource.cs(8,28,8,35): warning SA1400: Element 'baseDir' should declare an access modifier (https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1400.md)

## Version Info

1.4.1

## Additional Info

By adding `/// <auto-generated />` to the top of every emitted file, other analyzers are warned away from reporting frivolous diagnostics.

**Comment by svause-stryker** [comment]
@AArnott just curious if you figured out a way around this. I have tried every technique I could find to exclude the file with no luck.

**Comment by AArnott** [comment]
No. I don't use this package anyway. I can't remember how I came across it initially. Probably some user asked for my help to solve it and I realized it was a problem that needed to be solved here.

**Comment by viceroypenguin** [comment]
> just curious if you figured out a way around this. I have tried every technique I could find to exclude the file with no luck.

@svause-stryker I had to remove this package from my apps and reimplement. 

There are analyzers you can turn off, but they have to be done in the csproj instead of the .editorconfig. Besides, the analyzers are correct - string comparison should be done using case sensitive comparer, and I/O should not be done in a source generator. 

This won't be easily addressed by consumers until kzu reviews and merges #278 and #280, which I don't expect to happen anytime soon.

**Comment by svause-stryker** [comment]
Yup I just ripped it out and went a different way. Wasn't ultra important for what I needed it for.

**Comment by kzu** [comment]
Merged and released! https://github.com/devlooped/ThisAssembly/releases/tag/v1.4.2
